### ISSUE TITLE
HDMI not working

### ISSUE THREAD

**Issue by kapollo** [TechNexion-customization/meta-boot2qt#1]
I seems that the HDMI not working properly:
tested with 860d006c7f09d8ca60e531d4ff6d2e68f9ae1d67
built with qt 5.12.5 (replaced the meta layer with aforementioned commit) 

I get 
[    1.258486] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    1.265130] [drm] No driver support for vblank timestamp query.
[    1.271272] imx-drm display-subsystem: bound imx-dcss-crtc.0 (ops dcss_crtc_ops)
[    2.776650] [drm:hdp_fw_check] *ERROR* CDN_API_General_Test_Echo_Ext_blocking - echo test failed, check firmware!
[    2.776658] [drm:imx_hdp_imx_bind] *ERROR* Failed to initialise HDP firmware
[    2.794021] imx-drm display-subsystem: failed to bind 32c00000.hdmi (ops imx_hdp_imx_ops): -6
[    2.802686] imx-drm display-subsystem: master bind failed: -6

Tried with Dell monitors and dedicated panel with HDMI converter board

**Comment by po-cheng-technexion** [comment]
Try latest commit 94e7e100df02791623fa21c4d4060b42e3f5c15f with wic fixes, the meta-edm-bsp-release layer is also updated with relevant fixes.
